const express = require("express");
const cors = require("cors");
const bodyparser = require("body-parser");
const htmlpdf = require("html-pdf");

const pdfTemplate = require("./documents/index");

const app = express();
const port = process.env.PORT || 4000;

// Middleware
app.use(cors());
app.use(bodyparser.urlencoded({ extended: true }));
app.use(bodyparser.json());

app.listen(port, () => {
	console.log(`Listening in port number ${port}`);
});

// POST - to make server to genarate pdf
// GET - after making post request - again we need to ask the server to give the pdf generated by it


app.post("/createpdf", (req, res) => {
	console.log("Create pdf request");
	htmlpdf.create(pdfTemplate(req.data), {}).toFile("myresume.pdf", (err) => {
		if (err) {
			Promise.reject();
		}

		Promise.resolve();
	});
});

app.get("/getpdf", (req, res) => {
	console.log("Get Request for getting pdf");
	res.sendFile(`${__dirname}/myresume.pdf`);
});
