// Letter of credit Router 

// GET 
// @params 
// 
// <year:int> (start year)
//
// POST
// @params 
// 
// ! Cannot write huge number of parameter's here
// ! It affects readability
// 
// DELETE
// @params 
// 
// !xx
// 
// PATCH
// @params 
//
// !xx
// 
// @id 
// <year:int>

// Roles : 
// (i) create pdf
// (ii) send pdf
// (iii) delete pdf

// STATUS CODES
// 200 - Success Operation
// 201 - Success Creation
// 404 - Not found
// 500 - Server Error
// 403 - Forbidden Request

// Requirements
const express = require("express");
const cors = require("cors");
const path = require('path');
const bodyparser = require("body-parser");
const htmlpdf = require("html-pdf");
const util = require("./../../../controller/utils");

// BalanceSheet Router
const balanceSheetRouter = express.Router();

// Template
const pdfTemplate = require("../../../views/template/balanceSheet");

// Stores pdf with <year> as unique identifier

const gen_file_name = "balance_sheet";
const FILE_NAME = "balanceSheet.js";
const ROUTER_NAME = "balanceSheetRouter";

// Middleware
balanceSheetRouter.use(cors());
balanceSheetRouter.use(bodyparser.urlencoded({ extended: true }));
balanceSheetRouter.use(bodyparser.json());

// POST - to make server to genarate pdf
// GET - after making post request - again we need to ask the server to give the pdf generated by it

// Creates pdf
// notifies frontend that it has created the pdf
// Content : req.body

// Client will not about pdf storing in webs server 
balanceSheetRouter.post("/:year", (req, res) => {
	const debugText = util.RDebugText(FILE_NAME, "POST", ROUTER_NAME);
    console.log(debugText);
	
	const year = req.params.year;

	htmlpdf
		.create(pdfTemplate(req.body), {})
		.toFile(`${gen_file_name}_${year}.pdf`, (err) => {
			if (err) {
				console.log(util.ErrorStream(FILE_NAME,"CREATING",`${gen_file_name}-pdf not created`,err));
				res.send({err:err});
				Promise.reject();
			}
			console.log(util.DebugStream(FILE_NAME,"SUCCESS",`${gen_file_name}-pdf created`));
			res.send(Promise.resolve());
		});
});

balanceSheetRouter.get("/:year", (req, res) => {
	const debugText = util.RDebugText(FILE_NAME, "GET", ROUTER_NAME);
    console.log(debugText);

	const year = req.params.year;

	const curr_path = path.normalize(`${__dirname}\\..\\..\\..\\`);
	res.sendFile(`${curr_path}/${gen_file_name}_${year}.pdf`);
	console.log(util.DebugStream(FILE_NAME,"SUCCESS",`${gen_file_name}-pdf sent`));
});

module.exports = balanceSheetRouter;